name: publishable

on:
  push:
    branches:
      - master
      - releases/*

  pull_request:
    paths:
      - "tox_ltt/**"
      - "pyproject.toml"
      - "setup.cfg"
      - ".gitignore"
      - "CONTRIBUTING.rst"
      - "LICENSE"
      - "MANIFEST.in"
      - "README.rst"
      - "tox.ini"
      - "requirements-dev.txt"
      - ".github/workflows/publish.yml"

jobs:
  pypi:
    runs-on: ubuntu-latest

    steps:
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"

      - name: Upgrade and install additional system packages
        run: pip install --upgrade pip setuptools virtualenv wheel

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dev requirements
        run: pip install -r requirements-dev.txt

      - name: Run unit tests
        run: tox -e publishable
